### ISSUE TITLE
Does not play nice with `MooX::ProtectedAttributes`

### ISSUE THREAD

**Issue by vanHoesel** [tobyink/p5-sub-handlesvia#12]
Thanks for your hard work and dedication on `Moo` and `TypeTiny` and many more, it really helps to write nice code. So do many other `MooX::` extensions.

The following doe not work for obvious reasons:
```perl
package My::Client;

use Moo;
use MooX::HandlesVia;
use MooX::ProtectedAttributes;
use MooX::Should;

use Types::Standard qw/ArrayRef Bool Enum HasMethods Maybe Str/;

protected_has _client_halted => (
    is            => 'rw',
    should        => Bool,
    reader        => '_has_client_halted',
    default       => 0,
    handles_via   => 'Bool',
    handles       => {
       _halt_client => 'set'
    }
);
```

Neither does it when I would drop-in `Sub::HandlesVia`

But the following does work:
```perl
package My::Client;

use Moo;
use Sub::HandlesVia;
use MooX::ProtectedAttributes;
use MooX::Should;

use Types::Standard qw/ArrayRef Bool Enum HasMethods Maybe Str/;

has _client_halted => (
    is            => 'rw',
    should        => Bool,
    reader        => '_has_client_halted',
    default       => 0,
    handles_via   => 'Bool',
    handles       => {
       _halt_client => 'set'
    }
);
```

Would this be fixable ?

**Comment by tobyink** [comment]
The way that most extensions to Moo work is by taking `has` and wrapping it with a sub to intercept any attribute definitions. This can be a little unreliable when you start mixing multiple extensions to Moo.

By changing the order in which you `use` them, you *might* be able to make it work.

I will have a play around with it though and see what I can find out.

**Comment by vanHoesel** [comment]
Hey, thanks for your quick response!

Just to let you know, I'm not in a hurry now, I got a work around for now. I sadly moved back to the `MooX::HandlesVia` and added:
```perl
sub _halt_client {
    $_[0]->_client_halted(1)
}
```
which works fine.

I'm about to release a new version of `OpenTracing::Implementation::DataDog` with a completely updated version of the `DataDog::Client`.

I may try fiddling with the order of `use` commands, but I tend to keep them on alphabetical order :-)

**Comment by tobyink** [comment]
The following passes:

```perl
use strict;
use warnings;
use Test::More;

{
	package Local::Dummy;
	use Test::Requires 'Moo';
	use Test::Requires 'MooX::ProtectedAttributes';
	use Test::Requires 'MooX::Should';
	use Test::Requires 'Types::Standard';
};

{
	package Local::TestClass;
	use Moo;
	use Sub::HandlesVia;
	use MooX::ProtectedAttributes;
	use MooX::Should;
	use Types::Standard 'Bool';
	protected_has _client_halted => (
		is            => 'rw',
		should        => Bool,
		reader        => '_has_client_halted',
		default       => 0,
		handles_via   => 'Bool',
		handles       => {
			_halt_client => 'set',
		},
	);
}

my $client = Local::TestClass->new();
$client->_halt_client();
ok( $client->{_client_halted} );

done_testing;
```

The trick is to load MooX::ProtectedAttributes last, so that it sees the version of `has` which has already been tweaked by the other two modules.

If you need to load them alphabetically, try creating a module called "ZZZ::MooX::ProtectedAttributes" which is a simple subclass of MooX::ProtectedAttributes and use that instead.

I'll mention this issue in the documentation thoug.

**Comment by vanHoesel** [comment]
I'v been playing along...

My experience is that it is not because of `MooX::ProtectedAttributes` (although I have not tried it excluding that module).

It seems that this works:
```perl
use Moo;
use Sub::HandlesVia;
use MooX::Foo;
use MooX::Bar;
```

The `Sub::HandlesVia` MUST follow straight after `use Moo`. It fails when used before, it fails after any `MooX::*`

**Comment by tobyink** [comment]
> The Sub::HandlesVia MUST follow straight after use Moo

It is [documented](https://metacpan.org/pod/Sub::HandlesVia#DESCRIPTION) that it need to be used before Moo/Moo::Role/Moose/Moose::Role/etc. Otherwise it has no way of detecting what OO system you're using.

> it fails after any MooX::*

Depends on the MooX module. This will work, and would be my recommended order for loading them:

```perl
use Moo;
use MooX::Should;
use Sub::HandlesVia;
use MooX::ProtectedAttributes;
```

It allows Sub::HandleVia to "see" the changes MooX::Should makes to `isa`, and allows MooX::ProtectedAttributes to wrap a handles_via-enabled version of `has` instead of the standard Moo `has`.
